create extension if not exists pgcrypto;

create table if not exists public.projects (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  description text,
  default_template text not null default 'auto' check (default_template in ('auto','powder','assay','ratio')),
  output_product_name text,
  batch_prefix text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.conversions (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects(id) on delete cascade,
  source_file_name text not null,
  source_storage_path text not null,
  output_file_name text,
  output_storage_path text,
  template_type text check (template_type in ('powder','assay','ratio')),
  status text not null default 'processing' check (status in ('processing','ready','error')),
  product_name text,
  batch_number text,
  manufacturing_date date,
  extracted_data jsonb,
  warning_count integer not null default 0,
  error_message text,
  created_at timestamptz not null default now()
);

create index if not exists conversions_project_created_idx on public.conversions(project_id, created_at desc);

alter table public.projects enable row level security;
alter table public.conversions enable row level security;
-- No anon/authenticated policies are intentionally created. The app DB layer uses the server-only service role.

insert into storage.buckets (id, name, public) values
  ('coa-sources','coa-sources',false),
  ('coa-outputs','coa-outputs',false)
on conflict (id) do update set public = false;

create or replace view public.project_dashboard as
select p.*,
       count(c.id)::int as conversion_count,
       count(c.id) filter (where c.status='ready')::int as ready_count,
       count(c.id) filter (where c.status='error')::int as error_count,
       max(c.created_at) as last_conversion_at
from public.projects p
left join public.conversions c on c.project_id=p.id
group by p.id;

insert into public.projects (id,name,description,default_template,output_product_name,batch_prefix)
values ('11111111-1111-4111-8111-111111111111','Organic Chasteberry Powder','Sample project based on the supplied Chaste Berry COA.','powder','Organic Chasteberry Powder','OCP')
on conflict (id) do nothing;

-- Keep project/history data server-only. Signed Storage upload tokens are generated by the server.
revoke all on table public.projects from anon, authenticated;
revoke all on table public.conversions from anon, authenticated;
revoke all on table public.project_dashboard from anon, authenticated;
grant select, insert, update, delete on table public.projects to service_role;
grant select, insert, update, delete on table public.conversions to service_role;
grant select on table public.project_dashboard to service_role;
