import Link from "next/link";
import { requireAdmin } from "@/lib/auth";
import { listProjects } from "@/lib/repository";
import { isSupabaseConfigured } from "@/lib/supabase";
import { LogoutButton } from "@/components/logout-button";
import { NewProjectForm } from "@/components/new-project-form";

function date(v?:string|null){return v?new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",year:"numeric"}).format(new Date(v)):"No conversions yet"}
export default async function ProjectsPage(){await requireAdmin();const projects=await listProjects();const ready=projects.reduce((n,p)=>n+(p.ready_count||0),0);const errors=projects.reduce((n,p)=>n+(p.error_count||0),0);return <main className="app-shell"><header className="topbar"><div><span className="logo-chip">K</span><strong>COA Converter</strong></div><div className="top-actions"><span className="environment">{isSupabaseConfigured()?"Supabase connected":"Demo mode"}</span><LogoutButton/></div></header><div className="content"><div className="page-heading"><div><p className="eyebrow">PROJECT WORKSPACE</p><h1>Projects</h1><p>Every PDF conversion, Excel output, warning and history record stays inside its project.</p></div><NewProjectForm/></div><section className="stats"><div><span>Projects</span><strong>{projects.length}</strong></div><div><span>Ready Excel files</span><strong>{ready}</strong></div><div><span>Needs attention</span><strong>{errors}</strong></div></section><section><div className="section-head"><h2>Project grid</h2><span>{projects.length} project{projects.length===1?"":"s"}</span></div><div className="project-grid">{projects.map(p=><Link className="project-card" href={`/projects/${p.id}`} key={p.id}><div className="project-card-top"><span className="template-badge">{p.default_template}</span><span className="arrow">↗</span></div><h3>{p.name}</h3><p>{p.description||"No description"}</p><div className="project-metrics"><div><strong>{p.conversion_count||0}</strong><span>Conversions</span></div><div><strong>{p.ready_count||0}</strong><span>Ready</span></div><div><strong>{p.error_count||0}</strong><span>Errors</span></div></div><div className="project-footer"><span className="status-dot ready"></span><span>Last activity: {date(p.last_conversion_at)}</span></div></Link>)}</div></section></div></main>}
